name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          major_pattern: 'major:'
          minor_pattern: 'feat:'
          version_format: '${major}.${minor}.${patch}-prerelease${increment}'
        id: version

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          NEW_VERSION: ${{ steps.version.outputs.version_tag }}
        run: |
          echo "Start login"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "New version: $NEW_VERSION!!!"
          echo "End login"

      # - name: Build Docker Image
      #   run: |
      #     docker build -t sahz1998/docker-graphql:0.0.1 .
      #     docker build -t sahz1998/docker-graphql:latest .

      # - name: Push Docker Image
      #   run: |
      #     docker push sahz1998/docker-graphql:0.0.1
      #     docker push sahz1998/docker-graphql:latest

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
