name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Start login"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "End login"

      - name: Build Docker Image
        run: |
          docker build -t sahz1998/docker-graphql:0.0.1 .

      - name: Push Docker Image
        run: |
          docker push sahz1998/docker-graphql:0.0.1

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
